PGDMP                  
        x            db_first_project    12.2    12.2 @    y           0    0    ENCODING    ENCODING        SET client_encoding = 'UTF8';
                      false            z           0    0 
   STDSTRINGS 
   STDSTRINGS     (   SET standard_conforming_strings = 'on';
                      false            {           0    0 
   SEARCHPATH 
   SEARCHPATH     8   SELECT pg_catalog.set_config('search_path', '', false);
                      false            |           1262    40866    db_first_project    DATABASE     ˜   CREATE DATABASE db_first_project WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'English_Indonesia.1252' LC_CTYPE = 'English_Indonesia.1252';
     DROP DATABASE db_first_project;
                pg_write_server_files    false            Õ            1259    41217    dat_cart    TABLE     V   CREATE TABLE public.dat_cart (
    id bigint NOT NULL,
    id_user bigint NOT NULL
);
    DROP TABLE public.dat_cart;
       public         heap    postgres    false            Ô            1259    41215    dat_cart_id_seq    SEQUENCE     Ï   ALTER TABLE public.dat_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    213            Ø            1259    41387    dat_cart_produk    TABLE     ¨   CREATE TABLE public.dat_cart_produk (
    id_cart bigint NOT NULL,
    id_produk character varying(5) NOT NULL,
    jumlah_item numeric(5,0),
    id bigint NOT NULL
);
 #   DROP TABLE public.dat_cart_produk;
       public         heap    postgres    false            Ù            1259    41407    dat_cart_produk_id_seq    SEQUENCE     Ý   ALTER TABLE public.dat_cart_produk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_cart_produk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    216            Ò            1259    41124    dat_gambar_produk    TABLE     ”   CREATE TABLE public.dat_gambar_produk (
    id bigint NOT NULL,
    nama_gambar character varying(216),
    id_produk character varying NOT NULL
);
 %   DROP TABLE public.dat_gambar_produk;
       public         heap    postgres    false            Ó            1259    41127    dat_gambar_produk_id_seq    SEQUENCE     á   ALTER TABLE public.dat_gambar_produk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_gambar_produk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    210            Ñ            1259    41113    dat_kategori_produk    TABLE     w   CREATE TABLE public.dat_kategori_produk (
    id character varying(4) NOT NULL,
    kategori character varying(128)
);
 '   DROP TABLE public.dat_kategori_produk;
       public         heap    postgres    false            Ý            1259    41733    dat_notif_user    TABLE       CREATE TABLE public.dat_notif_user (
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    expired_date timestamp(0) with time zone NOT NULL,
    id_user bigint NOT NULL,
    action character varying(32) NOT NULL,
    id bigint NOT NULL
);
 "   DROP TABLE public.dat_notif_user;
       public         heap    postgres    false            Þ            1259    41745    dat_notif_user_id_seq    SEQUENCE     Û   ALTER TABLE public.dat_notif_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_notif_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    221            Ð            1259    41107 
   dat_produk    TABLE       CREATE TABLE public.dat_produk (
    id character varying(5) DEFAULT to_char(nextval('public.produk_seq'::regclass), '"P"fm000'::text) NOT NULL,
    kategori_produk character varying(4),
    nama_produk character varying(512),
    harga_produk numeric(15,0),
    stok_produk numeric(4,0),
    foto_produk1 character varying(512),
    foto_produk2 character varying(512),
    foto_produk3 character varying(512),
    foto_produk4 character varying(512),
    foto_produk5 character varying(512),
    deskripsi_produk character varying
);
    DROP TABLE public.dat_produk;
       public         heap    postgres    false            Ú            1259    41686    oauth_access_token    TABLE       CREATE TABLE public.oauth_access_token (
    token_id character varying(256),
    token bytea,
    authentication_id character varying(256),
    user_name character varying(256),
    client_id character varying(256),
    authentication bytea,
    refresh_token character varying(256)
);
 &   DROP TABLE public.oauth_access_token;
       public         heap    postgres    false            Î            1259    41080    oauth_client_details    TABLE     {  CREATE TABLE public.oauth_client_details (
    client_id character varying(256) NOT NULL,
    resource_ids character varying(256),
    client_secret character varying(256),
    scope character varying(256),
    authorized_grant_types character varying(256),
    web_server_redirect_uri character varying(256),
    autoapprove character varying(256),
    access_token_validity numeric(11,0) DEFAULT NULL::numeric,
    refresh_token_validity numeric(11,0) DEFAULT NULL::numeric,
    authorities character varying(256) DEFAULT NULL::character varying,
    additional_information character varying(4096) DEFAULT NULL::character varying
);
 (   DROP TABLE public.oauth_client_details;
       public         heap    postgres    false            Û            1259    41693    oauth_client_token    TABLE     Û   CREATE TABLE public.oauth_client_token (
    token_id character varying(256),
    token bytea,
    authentication_id character varying(256),
    user_name character varying(256),
    client_id character varying(256)
);
 &   DROP TABLE public.oauth_client_token;
       public         heap    postgres    false            Ü            1259    41699    oauth_refresh_token    TABLE     |   CREATE TABLE public.oauth_refresh_token (
    token_id character varying(256),
    token bytea,
    authentication bytea
);
 '   DROP TABLE public.oauth_refresh_token;
       public         heap    postgres    false            Ë            1259    41037    s_roles    TABLE     ¡   CREATE TABLE public.s_roles (
    id_role character varying(36) NOT NULL,
    name character varying(255) NOT NULL,
    label character varying(255) NOT NULL
);
    DROP TABLE public.s_roles;
       public         heap    postgres    false            Ì            1259    41047    s_user_roles    TABLE     n   CREATE TABLE public.s_user_roles (
    id_user bigint NOT NULL,
    id_role character varying(36) NOT NULL
);
     DROP TABLE public.s_user_roles;
       public         heap    postgres    false            Ê            1259    41015    s_users    TABLE     ?  CREATE TABLE public.s_users (
    id_user bigint DEFAULT nextval('public.s_users_seq'::regclass) NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fullname character varying(255) NOT NULL,
    active boolean NOT NULL
);
    DROP TABLE public.s_users;
       public         heap    postgres    false            ×            1259    41236    s_users_details    TABLE     Á   CREATE TABLE public.s_users_details (
    id bigint NOT NULL,
    no_hp character varying(13),
    foto_profil character varying(216),
    alamat character varying(2048),
    id_user bigint
);
 #   DROP TABLE public.s_users_details;
       public         heap    postgres    false            Ö            1259    41234    s_users_details_id_seq    SEQUENCE     Ý   ALTER TABLE public.s_users_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.s_users_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    215            m          0    41217    dat_cart 
   TABLE DATA           /   COPY public.dat_cart (id, id_user) FROM stdin;
    public          postgres    false    213            p          0    41387    dat_cart_produk 
   TABLE DATA           N   COPY public.dat_cart_produk (id_cart, id_produk, jumlah_item, id) FROM stdin;
    public          postgres    false    216            j          0    41124    dat_gambar_produk 
   TABLE DATA           G   COPY public.dat_gambar_produk (id, nama_gambar, id_produk) FROM stdin;
    public          postgres    false    210            i          0    41113    dat_kategori_produk 
   TABLE DATA           ;   COPY public.dat_kategori_produk (id, kategori) FROM stdin;
    public          postgres    false    209            u          0    41733    dat_notif_user 
   TABLE DATA           \   COPY public.dat_notif_user (username, email, expired_date, id_user, action, id) FROM stdin;
    public          postgres    false    221            h          0    41107 
   dat_produk 
   TABLE DATA           ¹   COPY public.dat_produk (id, kategori_produk, nama_produk, harga_produk, stok_produk, foto_produk1, foto_produk2, foto_produk3, foto_produk4, foto_produk5, deskripsi_produk) FROM stdin;
    public          postgres    false    208            r          0    41686    oauth_access_token 
   TABLE DATA           …   COPY public.oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) FROM stdin;
    public          postgres    false    218            g          0    41080    oauth_client_details 
   TABLE DATA           ï   COPY public.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, autoapprove, access_token_validity, refresh_token_validity, authorities, additional_information) FROM stdin;
    public          postgres    false    206            s          0    41693    oauth_client_token 
   TABLE DATA           f   COPY public.oauth_client_token (token_id, token, authentication_id, user_name, client_id) FROM stdin;
    public          postgres    false    219            t          0    41699    oauth_refresh_token 
   TABLE DATA           N   COPY public.oauth_refresh_token (token_id, token, authentication) FROM stdin;
    public          postgres    false    220            e          0    41037    s_roles 
   TABLE DATA           7   COPY public.s_roles (id_role, name, label) FROM stdin;
    public          postgres    false    203            f          0    41047    s_user_roles 
   TABLE DATA           8   COPY public.s_user_roles (id_user, id_role) FROM stdin;
    public          postgres    false    204            d          0    41015    s_users 
   TABLE DATA           W   COPY public.s_users (id_user, username, password, email, fullname, active) FROM stdin;
    public          postgres    false    202            o          0    41236    s_users_details 
   TABLE DATA           R   COPY public.s_users_details (id, no_hp, foto_profil, alamat, id_user) FROM stdin;
    public          postgres    false    215            }           0    0    dat_cart_id_seq    SEQUENCE SET     >   SELECT pg_catalog.setval('public.dat_cart_id_seq', 63, true);
          public          postgres    false    212            ~           0    0    dat_cart_produk_id_seq    SEQUENCE SET     E   SELECT pg_catalog.setval('public.dat_cart_produk_id_seq', 26, true);
          public          postgres    false    217                       0    0    dat_gambar_produk_id_seq    SEQUENCE SET     G   SELECT pg_catalog.setval('public.dat_gambar_produk_id_seq', 37, true);
          public          postgres    false    211            €           0    0    dat_notif_user_id_seq    SEQUENCE SET     C   SELECT pg_catalog.setval('public.dat_notif_user_id_seq', 6, true);
          public          postgres    false    222                       0    0    s_users_details_id_seq    SEQUENCE SET     D   SELECT pg_catalog.setval('public.s_users_details_id_seq', 2, true);
          public          postgres    false    214            Ö
           2606    41221    dat_cart dat_cart_pk 
   CONSTRAINT     R   ALTER TABLE ONLY public.dat_cart
    ADD CONSTRAINT dat_cart_pk PRIMARY KEY (id);
 >   ALTER TABLE ONLY public.dat_cart DROP CONSTRAINT dat_cart_pk;
       public            postgres    false    213            Þ
           2606    41417 "   dat_cart_produk dat_cart_produk_pk 
   CONSTRAINT     `   ALTER TABLE ONLY public.dat_cart_produk
    ADD CONSTRAINT dat_cart_produk_pk PRIMARY KEY (id);
 L   ALTER TABLE ONLY public.dat_cart_produk DROP CONSTRAINT dat_cart_produk_pk;
       public            postgres    false    216            Ø
           2606    41591    dat_cart dat_cart_un 
   CONSTRAINT     R   ALTER TABLE ONLY public.dat_cart
    ADD CONSTRAINT dat_cart_un UNIQUE (id_user);
 >   ALTER TABLE ONLY public.dat_cart DROP CONSTRAINT dat_cart_un;
       public            postgres    false    213            Ô
           2606    41136 &   dat_gambar_produk dat_gambar_produk_pk 
   CONSTRAINT     d   ALTER TABLE ONLY public.dat_gambar_produk
    ADD CONSTRAINT dat_gambar_produk_pk PRIMARY KEY (id);
 P   ALTER TABLE ONLY public.dat_gambar_produk DROP CONSTRAINT dat_gambar_produk_pk;
       public            postgres    false    210            Ò
           2606    41117 *   dat_kategori_produk dat_kategori_produk_pk 
   CONSTRAINT     h   ALTER TABLE ONLY public.dat_kategori_produk
    ADD CONSTRAINT dat_kategori_produk_pk PRIMARY KEY (id);
 T   ALTER TABLE ONLY public.dat_kategori_produk DROP CONSTRAINT dat_kategori_produk_pk;
       public            postgres    false    209            Î
           2606    41087 .   oauth_client_details oauth_client_details_pkey 
   CONSTRAINT     s   ALTER TABLE ONLY public.oauth_client_details
    ADD CONSTRAINT oauth_client_details_pkey PRIMARY KEY (client_id);
 X   ALTER TABLE ONLY public.oauth_client_details DROP CONSTRAINT oauth_client_details_pkey;
       public            postgres    false    206            Ð
           2606    41112    dat_produk produk_pkey 
   CONSTRAINT     T   ALTER TABLE ONLY public.dat_produk
    ADD CONSTRAINT produk_pkey PRIMARY KEY (id);
 @   ALTER TABLE ONLY public.dat_produk DROP CONSTRAINT produk_pkey;
       public            postgres    false    208            È
           2606    41046    s_roles s_role_name_key 
   CONSTRAINT     R   ALTER TABLE ONLY public.s_roles
    ADD CONSTRAINT s_role_name_key UNIQUE (name);
 A   ALTER TABLE ONLY public.s_roles DROP CONSTRAINT s_role_name_key;
       public            postgres    false    203            Ê
           2606    41044    s_roles s_role_pkey 
   CONSTRAINT     V   ALTER TABLE ONLY public.s_roles
    ADD CONSTRAINT s_role_pkey PRIMARY KEY (id_role);
 =   ALTER TABLE ONLY public.s_roles DROP CONSTRAINT s_role_pkey;
       public            postgres    false    203            Â
           2606    41026    s_users s_user_email_key 
   CONSTRAINT     T   ALTER TABLE ONLY public.s_users
    ADD CONSTRAINT s_user_email_key UNIQUE (email);
 B   ALTER TABLE ONLY public.s_users DROP CONSTRAINT s_user_email_key;
       public            postgres    false    202            Ä
           2606    41022    s_users s_user_pkey 
   CONSTRAINT     V   ALTER TABLE ONLY public.s_users
    ADD CONSTRAINT s_user_pkey PRIMARY KEY (id_user);
 =   ALTER TABLE ONLY public.s_users DROP CONSTRAINT s_user_pkey;
       public            postgres    false    202            Ì
           2606    41051    s_user_roles s_user_role_pkey 
   CONSTRAINT     i   ALTER TABLE ONLY public.s_user_roles
    ADD CONSTRAINT s_user_role_pkey PRIMARY KEY (id_user, id_role);
 G   ALTER TABLE ONLY public.s_user_roles DROP CONSTRAINT s_user_role_pkey;
       public            postgres    false    204    204            Æ
           2606    41024    s_users s_user_username_key 
   CONSTRAINT     Z   ALTER TABLE ONLY public.s_users
    ADD CONSTRAINT s_user_username_key UNIQUE (username);
 E   ALTER TABLE ONLY public.s_users DROP CONSTRAINT s_user_username_key;
       public            postgres    false    202            Ú
           2606    41243 "   s_users_details s_users_details_pk 
   CONSTRAINT     `   ALTER TABLE ONLY public.s_users_details
    ADD CONSTRAINT s_users_details_pk PRIMARY KEY (id);
 L   ALTER TABLE ONLY public.s_users_details DROP CONSTRAINT s_users_details_pk;
       public            postgres    false    215            Ü
           2606    41245 "   s_users_details s_users_details_un 
   CONSTRAINT     `   ALTER TABLE ONLY public.s_users_details
    ADD CONSTRAINT s_users_details_un UNIQUE (id_user);
 L   ALTER TABLE ONLY public.s_users_details DROP CONSTRAINT s_users_details_un;
       public            postgres    false    215            â
           2606    41356    dat_cart dat_cart_fk 
   FK CONSTRAINT     z   ALTER TABLE ONLY public.dat_cart
    ADD CONSTRAINT dat_cart_fk FOREIGN KEY (id_user) REFERENCES public.s_users(id_user);
 >   ALTER TABLE ONLY public.dat_cart DROP CONSTRAINT dat_cart_fk;
       public          postgres    false    213    202    2756            ä
           2606    41390 "   dat_cart_produk dat_cart_produk_fk 
   FK CONSTRAINT     ¬   ALTER TABLE ONLY public.dat_cart_produk
    ADD CONSTRAINT dat_cart_produk_fk FOREIGN KEY (id_produk) REFERENCES public.dat_produk(id) ON UPDATE CASCADE ON DELETE CASCADE;
 L   ALTER TABLE ONLY public.dat_cart_produk DROP CONSTRAINT dat_cart_produk_fk;
       public          postgres    false    208    2768    216            å
           2606    41395 $   dat_cart_produk dat_cart_produk_fk_1 
   FK CONSTRAINT     ª   ALTER TABLE ONLY public.dat_cart_produk
    ADD CONSTRAINT dat_cart_produk_fk_1 FOREIGN KEY (id_cart) REFERENCES public.dat_cart(id) ON UPDATE CASCADE ON DELETE CASCADE;
 N   ALTER TABLE ONLY public.dat_cart_produk DROP CONSTRAINT dat_cart_produk_fk_1;
       public          postgres    false    213    2774    216            á
           2606    41382    dat_produk dat_produk_fk 
   FK CONSTRAINT     ²   ALTER TABLE ONLY public.dat_produk
    ADD CONSTRAINT dat_produk_fk FOREIGN KEY (kategori_produk) REFERENCES public.dat_kategori_produk(id) ON UPDATE CASCADE ON DELETE RESTRICT;
 B   ALTER TABLE ONLY public.dat_produk DROP CONSTRAINT dat_produk_fk;
       public          postgres    false    2770    209    208            à
           2606    41057 %   s_user_roles s_user_role_id_role_fkey 
   FK CONSTRAINT     ‹   ALTER TABLE ONLY public.s_user_roles
    ADD CONSTRAINT s_user_role_id_role_fkey FOREIGN KEY (id_role) REFERENCES public.s_roles(id_role);
 O   ALTER TABLE ONLY public.s_user_roles DROP CONSTRAINT s_user_role_id_role_fkey;
       public          postgres    false    204    2762    203            ß
           2606    41052 %   s_user_roles s_user_role_id_user_fkey 
   FK CONSTRAINT     ‹   ALTER TABLE ONLY public.s_user_roles
    ADD CONSTRAINT s_user_role_id_user_fkey FOREIGN KEY (id_user) REFERENCES public.s_users(id_user);
 O   ALTER TABLE ONLY public.s_user_roles DROP CONSTRAINT s_user_role_id_user_fkey;
       public          postgres    false    2756    202    204            ã
           2606    41251 "   s_users_details s_users_details_fk 
   FK CONSTRAINT     ¬   ALTER TABLE ONLY public.s_users_details
    ADD CONSTRAINT s_users_details_fk FOREIGN KEY (id_user) REFERENCES public.s_users(id_user) ON UPDATE CASCADE ON DELETE CASCADE;
 L   ALTER TABLE ONLY public.s_users_details DROP CONSTRAINT s_users_details_fk;
       public          postgres    false    215    2756    202            m      xœ31ä4ä25á45á23â47äŠÑãââ %Ž      p   D   xœ-ËÉ€0CÑ³\3’—$]P ý×A>¾ùR·ÆBe±Á‘ 8~°,ã/	±áHßLœp(ûeÏef/ð²'      j   
   xœ‹Ñãââ Å ©      i   3   xœó600æôpôs	ðð÷såò600äôö÷

q
ñŒ8}Bü¸bô¸¸¸ ý«
U      u   W   xœÁÁ
€  ÐóöÞ£ØdxêCº¬$	’…
áß÷žVë+A·¤zÄû-Ú4ë–²ÞÏtZ!¡‘eäÙ±$Ax žá²’¬¹Wký¬DXpŸñ4¦Û      h      xœíÝA«%¹y€áuÏ¯è•—Î=RU©ŠCÀ!ÆfˆÉÂ`03ÆB7v²È¿Ï¹=é£ÎùÜ}…BDÏÐ›ÏB½ùøÄËéú.íåÝ/_^ò»_üË¯~õÛýÝ-åÞÝòíÝ?}ÿï?|ÿ—ßwG¿¿ýô_?üéÿœ¤p’ÃÉöñäw¿~÷³?ÿÉüð×ÿí¯¿}ÿ‹üÍ/ÿùÛï~óíû¿qöãÑ{Žã8Žã8îÿ…ûÙß}øùcüòÿLþ·à8Ž?%'¿8ÇqÇq7j1´%rÇý8¿ù.íçgiûøRÚ>CÚ>CÚ>CÚ>¥mŽã8Žã¸Õ·9Çq\ß”œüâÇqÇqÜ¨ÅÐ–Èq÷HÛÇí³´ý…²}ÜžËöý$…“N”mŽã8Žã¸Å§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËvj(Û)”íÊv
e;)ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–íÜP¶s(Û9”íÊvV¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["Çq\-Û{CÙÞCÙÞCÙÞCÙÞ•mŽã8Žã¸Õ§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËvi(Û%”íÊv	e»(ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–í³¡lŸ¡lŸ¡lŸ¡lŸÊ6ÇqÇqÜêÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž{”ír{»l—ÛsÙ¾Ÿ¤p’Ã‰²ÍqÇq·¸ó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙN
e;…²BÙN¡l'e›ã8Žã8nuçiÎq×7%'¿8ÇqÇq7j1´%rÇÕ²Êve;‡²CÙÎÊ6ÇqÇqÜêÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«e{o(Û{(Û{(Û{(Û»²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙ.
e»„²]BÙ.¡le›ã8Žã8nuçiÎq×7%'¿8ÇqÇq7j1´%rÇÕ²}6”í3”í3”í3”íSÙæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰Çq²½ß^Ëvú±lß¾¶÷ÛsÚ¾Ÿ¤p’Ã‰´ÍqÇq·¸ó6ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÚNŸ¥íô¥´BÚN!m§¶“´ÍqÇq·ºó6ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÚÎŸý{äùKi;‡´CÚÎ!mgi›ã8Žã8nuçmÎq×7%'¿8ÇqÇq7j1´%rÇÕ´½–¶·/¥í=¤í=¤í=¤í]Úæ8Žã8Ž[Ýy›sÇõMÉÉ/ÎqÇqÇZm‰ÇqŸÒö­|üÕöíÇ´ý·ËöÝ<•í×“Nr8Q¶9Žã8ŽãwžæÇq}Srò‹sÇqÇq£C["Çq\-Û{CÙ~þÍöëÉsÙ~þÍöë‰²ÍqÇq·¸ó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙ>ÊöÊöÊöÊö©lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸GÙ>oo—íóö\¶ï')œäp¢lsÇqÇ-î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶SCÙN¡l§P¶S(ÛIÙæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰Çqµlç†²CÙÎ¡lçP¶³²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙÞÊöÊöÊöÊö®lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶Ï†²}†²}†²}†²}*ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8îQ¶¯ÛÛeûº=—íûI
'9œ(ÛÇqÇq‹;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–íÔP¶S(Û)”íÊvR¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["Çq\-Û¹¡lçP¶s(Û9”í¬lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶÷†²½‡²½‡²½‡²½+ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–í³¡lŸ¡lŸ¡lŸ¡lŸÊ6ÇqÇqÜêÎÓœã8®oJN~qŽã8Žã8nÔbhKä8ŽûT¶ÓËíÍ²}7Oeûõ$…“N”mŽã8Žã¸Å§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËvj(Û)”íÊv
e;)ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–íÜP¶s(Û9”íÊvV¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["Çq\-Û{CÙÞCÙÞCÙÞCÙÞ•mŽã8Žã¸Õ§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËöÙP¶ÏP¶ÏP¶ÏP¶Oe›ã8Žã8nuçiÎq×7%'¿8ÇqÇq7j1´%rÇ=ÊöíövÙ¾ÝžËöý$…“N”mŽã8Žã¸Å§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËvj(Û)”íÊv
e;)ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–íÜP¶s(Û9”íÊvV¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["Çq\-Û{CÙÞCÙÞCÙÞCÙÞ•mŽã8Žã¸Õ§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËöùZ¶Ó×ËöÊöÊöÊö©lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸GÙN··Ëvº=—íûI
'9œ(ÛÇqÇq‹;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–íÔP¶S(Û)”íÊvR¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["Çq\-Û¹¡lçP¶s(Û9”í¬lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸OeûV¶×²}ûZÙ¾›§²ýz’ÂI'Ê6ÇqÇqÜâÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«eûh(ÛG(ÛG(ÛG(Û‡²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙ.
e»„²]BÙ.¡le›ã8Žã8nuçiÎq×7%'¿8ÇqÇq7j1´%rÇÕ²}5”í+”í+”í+”íKÙæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰Çq²}¾¼]¶Ï—ç²}?Iá$‡e›ã8Žã8nqçiÎq×7%'¿8ÇqÇq7j1´%rÇÕ²½5”í-”í-”í-”íMÙæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰Çqµl
eûeûeûeûP¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["Çq\-Û¥¡l—P¶K(Û%”í¢lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶¯†²}…²}…²}…²})ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8îQ¶¯—·Ëöõò\¶ï')œäp¢lsÇqÇ-î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶·†²½…²½…²½…²½)ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–í£¡l¡l¡l¡lÊ6ÇqÇqÜêÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«e»4”íÊv	e»„²]”mŽã8Žã¸Õ§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËöÕP¶¯P¶¯P¶¯P¶/e›ã8Žã8nuçiÎq×7%'¿8ÇqÇq7j1´%rÇ}*ÛéååÍ²}7Oeûõ$…“N”mŽã8Žã¸Å§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËöÖP¶·P¶·P¶·P¶7e›ã8Žã8nuçiÎq×7%'¿8ÇqÇq7j1´%rÇÕ²}4”í#”í#”í#”íCÙæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰Çqµl—†²]BÙ.¡l—P¶‹²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙ¾ÊöÊöÊöÊö¥lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸GÙ¾½¼]¶o/Ïeû~’ÂI'Ê6ÇqÇqÜâÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«e{k(Û[(Û[(Û[(Û›²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙ>ÊöÊöÊöÊö¡lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶ËkÙN_/Û%”íÊv	e»(ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–í«¡l_¡l_¡l_¡l_Ê6ÇqÇqÜêÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž{”íôòvÙN/Ïeû~’ÂI'Ê6ÇqÇqÜâÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«e{k(Û[(Û[(Û[(Û›²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9Žãe{ÿX¶óWËöÊöÊöÊö®lsÇqÇ-ï<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸ú›í½á7Û{øÍö~³½‡ßlïÊ6ÇqÇqÜêÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«eûl(Ûg(Ûg(Ûg(Û§²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9Žãe;ßÞ.Ûùö\¶ï')œäp¢lsÇqÇ-î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶SCÙN¡l§P¶S(ÛIÙæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰Çqµlç†²CÙÎ¡lçP¶³²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙÞÊöÊöÊöÊö®lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶KCÙ.¡l—P¶K(ÛE   Ùæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰ÇqµlŸ
eûeûeûeûT¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["ÇqÜ£lo··Ëöv{.Û÷“Nr8Q¶9Žã8ŽãwžæÇq}Srò‹sÇqÇq£C["Çq\-Û©¡l§P¶S(Û)”í¤lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶sCÙÎ¡lçP¶s(ÛYÙæ8Žã8Ž[ÝyšsÇõMÉÉ/ÎqÇqÇZm‰Çqµlï
e{e{e{e{W¶9Žã8ŽãVwžæÇq}Srò‹sÇqÇq£C["Çq\-Û¥¡l—P¶K(Û%”í¢lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶Ï†²}†²}†²}†²}*ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8îQ¶÷ãµlç¯–íýx.Û÷“Nr8Q¶9Žã8ŽãwžæÇq}Srò‹sÇqÇq£C["Çq\-ÛWCÙ¾BÙ¾BÙ¾BÙ¾”mŽã8Žã¸Õ§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–Èq÷(ÛÇËÛeûxy.Û÷“Nr8Q¶9Žã8ŽãwžæÇq}Srò‹sÇqÇq£C["Çq\-Û[CÙÞBÙÞBÙÞBÙÞ”mŽã8Žã¸Õ§9Çq\ß”œüâÇqÇqÜ¨ÅÐ–ÈqWËvÃw¶ðí#|gûßÙ>|g›ã8Žã8nyçiÎq×7%'¿8ÇqÇq7j1´%rÇÕ²Ýðí#|gûßÙ>Âw¶ßÙæ8Žã8Ž[ÞyšsÇõMÉÉ/ÎqÇqÇZm‰Çq²]¾³]Âw¶KøÎv	ßÙ.¾³ÍqÇq·¼ó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙnøÎv	ßÙ.á;Û%|g»øÎ6ÇqÇqÜòÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«e»á;Û%|g»„ïl—ðíâ;ÛÇqÇqË;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8îQ¶ÓÇ²¾Z¶S(Û)”íÊvR¶9Žã8Žã–wžæÇq}Srò‹sÇqÇq£C["Çq\-Û¥¡l—P¶K(Û%”í¢lsÇqÇ­î<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶¯†²}…²}…²}…²})ÛÇqÇq«;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8îQ¶óËÛe;¿<—íûI
'9œ(ÛÇqÇq‹;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–í­¡lo¡lo¡lo¡loÊ6ÇqÇqÜêÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž«eûh(ÛG(ÛG(ÛG(Û‡²ÍqÇq·ºó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙnøÎvßÙÎá;Û9|g;ûÎ6ÇqÇqÜòÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž{”í­á;Û[øÎö¾³½…ïlo¾³ÍqÇq·¼ó4ç8Žë›’“_œã8Žã8ŽµÚ9ŽãjÙnøÎö¾³½…ïloá;Û›ïlsÇqÇ-ï<Í9Žãú¦ääç8Žã8ŽãF-†¶DŽã¸Z¶¾³½…ïloá;Û[øÎöæ;ÛÇqÇqË;OsŽã¸¾)9ùÅ9Žã8Žã¸Q‹¡-‘ã8®–í†ïloá;Û[øÎö¾³½ùÎ6ÇqÇqÜòÎÓœã8®oJN~qŽã8Žã8nÔbhKä8Ž{”í½á;Û{øÎö¾³½‡ïlï¾³ÍqÇq·¼ó4ç8Žë›’“_œã8Žã8ŽµÚ9Žãe»üïo¶ÿáüËûw·ýåãïöZ¨KøÅv	¿Ø.áÛåÓ/¶??Ù?žÜ'ð¿}ÿá?ÿüáýßÿé¿þúþþï—ùÝO¿ùæ›ÿ1»÷      r   m  xœíšÝrä¶…¯w&…ïâ’ Ê©J%U‰]•ÇÏwäGÉÚXVraË»š!€F÷é¿p7×§¸m~Bm5uJì-5—|ˆ9åo?ýôïeÛ›s.×Xƒs)–^C©aç»ãÓ\öRŠ/­äZm|ÕxÉ%Ö¬95Õ9ì¥Ï÷T¦ø†$V4þÞÃž³‹ÆËVSêé63yf"‹ýP‰Ù+3w·­aÞcñkHº¹’6ç|F“Ä»¢Òù¾%éYL·Æ.ÇHM¬êi+ÏØ=tÛu.[èIó\\%Ó-ì?U‡Ìð¸Ú»7V'›—õë²¡„eºÛ!QTûo Ú_¡ÚPí¨ö+Žù


õT¾uŒ¿ƒJ–'Ò±FR2ºœk}¸®-6ì²-G4>l»íZä¼ž«w®îö¤G´!â”³ßtØ‘.Ú7¥‰qì9¼…Ð´çÍ»²m®¯>/ü½–K%¡‰wj`/íãŸîó ÛeWÛ²ù-úR\ó."5¤bÑ±Éh#k¢P©!ÍBÓ‰yIÖáqwù¯Ôê¦ãóù;™
š¤¬ÕÒÕ0qû]×¶Â¤\§ugëm›zˆ­Òòëaµ{*	ˆé¦²lsöÍ­sÚÝ4ðt²àÅÞ´ˆ/ò—Ÿýˆ[{š“¡žñ3æ&|á±)1rz~}f›ËR-›wÌ1•ÁI±„ÐbˆSœãÄ§Ä'òŽOs¬%W‹
kgs¼b=2@À¹×x^|ä/^[&‚kF?›×
›Ïlm&'æ™ç£Jn_R%ï5Éä$ÛCo=ÕçÖÜ6¯õˆ·kÜé›#SRúêúÿ–%5îÞíhMWh)ïKÞ®*	ÿM<Ó‚gƒ(sêüYŠ\—4GŸv}ÒØfV—©W—¼ä‰N¢èG>7™
“ø¬$5É3ójØÁkœgÄTt6¿ÉY°7Øxâ»­ŸkÅ0¼Ì~òžÏD2ÏÏùc¿*+ˆyu6ÛwËÂ­€“ÏSöçúè4/)G#}U˜ò›lEÌCþO’;ì2übšøËIž!v¬Ï‹Ù™†\ž'\$
AÊ×lv$<‰ÞeÆ~ÆñóY¹ðüÖ¼,guì•Ú3+¯ñÀÂ:›/•4{6j;Õð´“ì%.^ã¸eYcÄþ£¯æ;Ð’ðøÎä~çùnþ¬ìƒ|lm<ñb8"Ê£x0{Uç¢|{úJX9+ST*Èò9d'­Ux.qÐèÿœú.©	/ö­ÒGú²—pÂçÄæÕdÏ›>Ç(¿‚x†OŸgûž$Ç¢˜üÎ—#^wóãnqAgá2ì\,#dW`<(‰fÈ«ñ.#.ËjûXædªc%­ 3UŸ•ÙYüyŒöÜ[±m^ ±bYª6R~¯ ØÐµ¦rîUNäOfM JýoYë{V»ê½O“ÕŽ…ÒÑr tPIÊX¬Kƒª|—{¦&
Adó¹Œ¥KÇÔÑM‘™@@±¬Ž/‹ÕU„BðÍ&OáÅ)ÓÒ³…ÈË†žyGƒjA{Y+¤°kÎÊ³íð²'VriÊåìÊó¢þLF‚ŽU­j5†x'Ô¡ˆ½P%}õ%ÊBª®PÂ ‚•ŽGÔíD”áµ%ÒÙälVØ¢l¶8bâ4ªõÙ¦üUu®Ä	¶
>Só©UªÎh7jGÌ Fµ‚~`ÉZ‰uª‡§ZMV×›5_‘xa_°¾²k Ax›Í£KËÓªg–åø&'u ¥L¦ÅãcÄPðnU-Ô1ùx"'œÔÖ*bu·PïHèOÎR'O‘¼'æ„åÕc¿3Ÿ®]äØ(t·®NI}Æ¢ñºÍºÝÙ5II,Ø­»é™xœ/ªHy0èÉù6‡æ§>¯“ËùÆ¬´Ïöû<›ïgHnkÞ{õ×ži¼U¿Þ8Ï<‘×ÿ†©û1ÚÈ£9·–C÷6>Ö¯ø”!U!¼þ/ÛRú’g›…œÅÄ[ºa%tigE£»Q¼°åïÕ²F<EŒcðY³	|cD\)îÌîƒ³‹±xc,ð[Ü¹ýÉ8>™q|nçW§íêÑb _ßù™ëòl{3}
ªÄsÌèèüô/æ©Ê±jïÁ[­Óü–Ç<âA: ËWw~FØ5ÓÑyBW©Š¯¢šÎ©L§ XZpàl®]YTçç¤KÀT_%-8{‡&¯f¡¿³£Ãr¥¾x+ñ(a£SIYtÄ§o,É³E¦GRœ1æÕÐ€JÉ'u<X
9XÙ4%Iù¨î[¨‹²V>J’¢:æsz “Dº(öƒö’;ŠîŒvÙ¢D1L…ªTì«:¿#GL¶X]î¬òŠfS't– /Q{“<Š¼§ÞóxW,dQ7CKe)Çª,Û«º"óÀÂ›=¦žkVOEˆ2©LÂ ½¦‘%æ½Ñ©9ãÍŒd 8nQ½•ïô]º	š2‘U ,æ£óuõb,"çªZ]’8¿ˆÊ*¤Å)qN§–¦A@”ê”g7rH©³±Nð'cð~+úÌŸ®ûFŒAb81¢8BN1u|\G=´sFQ÷ß]©÷Û³î­È~ÜínÎˆÞõÛ´îûâ´©¯ë¼Ì´S
OïÓ²·÷|ûõ_û?é$ß¶¿ýuÿû/Ë¯¿ü¼ý£íOîEýg‹Gwªvó£Bç{¸
ŸÆÝ!sâý¬¾¶¤;”àU]´*Ø
•ºa«Ç­”zNÔÕÛé8Ž®·Ï»|¥ÿ«[ÈûÞãÐwÕÜ÷¬3=ÃïÒsÜ]çÐßÛÇX<Z‡Gß‘?•SñàbøïÌ¾ßw´¸,aª;üšBácŠv·ÙÞØO¬kwŸÇx:2ÃðÿQ¾gÒªù•“ŠfRÞ¸ñMâGË1ØâyëF‹ùŽ»)§kê›ën­Ý¦2çµªÍóçoÞÖsNßÿÏøy[•.Ì:>ÕEw§âžó©{&ß§Š™#”Ÿ›1bo·Ð:Íõ¸ß»ÝØÒÎnŸG
¿#âÏÜÚ_ÆšF©¾Æ{•zðëŸ¯f?^ûpõ¥ñöíGÞ2·~äÝ?ã,bÛ:§nßu³yâ¾¨Çåkêùc=|y«n¶WËq~ÜMÖoeö-Ž.7»iÜšžqûáw_ëèv/l‘œ‡­çû¨
o¸¬Z¯dW¹WÆg=eh]•’)æÄÊ÷­~x·ÕÆúêZ­ó
×õ¶ÀªEœþÀX	vêÍ/l,t‚%îº”ym£˜Þbø:¡Z'0›üäÇ¹ô&	Žåoz¦ã-Ói_xõfðjùÈ«ýºß-£UÃü™÷&#&»ç¨:uöêÙé•Òµ~¶»æ—úùÿ÷noÜ#¼Ž°^/oQí
Ù@qÜZ¼ÌÂ~Æ‘½óžÔáØ}	Ýª¡ØŽ×ýgé1‹®ÎtËúD¶îâ ‹œ2âñvN·ÐG•~ÔÊ‡g¹p•þ u¾FFÖ™ë‹¾~éÚ™óŸwU÷»*w¹÷¤š¼­‰3_ž[^ÞâÛ_WühTºj3â³Ú›zþbo‘§¯>íh·wµýâùç{ûóm¸ÕÚ¨Ó¹Iü ï ûäCáèþñ¨
§oŒüöÎóøW§UbÎæ\ßŠžŸã5"\}ò^þ‘3ž£ý.ƒC¶»1¨Oa“çÉðñÌqÇö):Æ˜ÈÌñ/>¨“ÖÕk÷Ë;s„ûWÏæX]o³òs¬ß’êô–k?ëÓÇØš³$é!N^0­©¾ˆ«û¸ñ{?~.‘ßë„9™ÖG
mmž²›ãœ÷ÆFë¥Vl)_áÕðä\`=¡Õƒ¯Œ>üÔûge}©£ÿÕSƒñ/R¾-;A>Ïê¶µÉ-5÷u-ÓÖzŸZž÷ï?ýåû÷ïÿb:˜      g   ô   xœµÐMKÃ@àóæwäšµ­zµT!J{)„IvÓŒÙ/f'úëM=ˆ7Aæ0¼—yÞ±¾A£!Ñhï@"]Bz#Sî_Ê'Yî·îùøfw{í^¨ãö<ìÔíA®ËðP^¦î@«®z5Ï‘ 
*›Yg ,: ÆÉ“ÊHw¤c_³´=sØä¹ñ-˜ÞGÞ²9Ì{0^œªï“´µãÀ~jÿ‰Š6l‘…ƒ‘ûÖ«?²òÝ\´Ö
9caˆX[íÆ]¹n`NÏâzÖ^€Ñ»ú
øéÑë¥”‚iÔ¢¸[ÏëWÓ"I’Ï¼¯Ð      s   
   xœ‹Ñãââ Å ©      t   )  xœ½XYvÜ8üžf7ä]òC‰äæøSJjµÝv’'vb·D
…Ím¸ÍÕZœ{/®©ÌmËeïs–.uüóýûmÝ9'58—ö<5d
ÏŸjY3^dŸ{U[ß¸ž%GîÑ¤5Œ<³ÇsÊ%<E<w|Ï<ÂH	»3×ó®)‰u8wÈO3]'%p'V Q.’p~Ã›fŸIs¬½»½nê ­óiÇÏ–ò<¤TÞ©	Ë´§ánÓn¨yÚpŸÄ
çhuú+Vÿ„•‡wEI=É¸Y)´rgh[¸Û–w¬Aç0%B¯Ã³Ïawt§jj¹ä@sMÿ›Dm©FŸŸ#-²ê¤Q}mÒ¤¤j'<ñ¹§=Öñ9J®Ø§Zpƒç:Þëèlÿ¸ä4àl=áÙÎ?­WU†à¾òÞ×"ÞŸû×}J+z„.ÙÛ½»×½ñçùè¸÷Áo1$bŽßÀz^â_¢Üe—áSÁGy†Øq^šÙ™–\¼O@r;4“BíHð4ôÎöc<Ø"ÎIßÜ'äüŽ•4ûb„ÎÙ~ªÄ}°gOç.< c¢½àÍ{w¡e1FØ¿pôj¾Zô¼|+x3ñ~˜?÷@>líxãÍ>àÀÌégöî”Oßž~ ƒ¬,àJ‰ºfÈòÄQk<Åº‚ŠðÏ©oKxá^¥>Ôw'øü‚yšì}g@HŒô+ð žáÀÓKµçD9ÆbÄq^¸|æÇa¼ …¸,;›Eí
XŒWðÂŸònýÂeñ2ovEŽ ›`-§
èõÂÈÏ5?^Cû’G„­°­/ ±Á²¤¶¢
¿7 Ø¡«¦]sòL7ô'³% ÁFáù)<"¡ƒ{ÅrKCjŠÐ:H@f˜p€’IŒ˜!*£DßÉäS"Ä¼f1Oê˜&tÀ¥™€ ¹ ¹X\¢DBà›ž‚‹8	ÌCÏ¼ÃŒl{ZK¤`WÆÙ~xÙƒ
b©ˆ±·â=2ØÎˆ:–µÔrø: ­î¥ô
¨·H‘÷ˆY£u™7eðZ‹‚ˆOÌ{¤ÍÆ#ÜÞ 
%ÛÁÄ/³·‚'°•Èà3jr³7´[¹#
C¶°¨ApÙÃ#[Ëû9J
­Âmðn
@Ð¡Üb¡§™Ï,Ê'ø˜ÀªRŒä˜"|1ÈNð®2Žò}\Žjó¸º!û³Fá&Øä2ò$ù÷àCM°\=,ð«Þ»qÕqÕÇqÖG¢\<êÏ&¨v¾‚®ø²š¢®ð³ÃY„ÓŽÔXµ¼è'üWUV;=iC¦_ðæ^OÏOVCiE|t[G¹Ü\ðÌøÀÓî`5µ+½B
X‚ùÛÜ
p(îW?4 ÿ|§ÿ|Ò¾Ó¾íwÇÚyc7÷~fé~KÏ¸ó³{®^IÃ£ŸÈ‡?}ººÏLõ™6Ž©ÇÖBÑD¸Õ1Eiôî÷	k8Ö·k}.±ÃðöùƒÎ‘ýkX.=1ij~Eäpç!åƒ
¹1à½ÉX=Ž[¼ ¨_Åã‹[NG¾Ökò™¹·Vj0w7ªñ&c/h,oÝdÊÇžOûäcÏéû°‰v/öûš ¿¸ªNõ÷¾—\€ê:¨µåC
%ã•.^ƒMõÔ]Kñ=ø^+’¬¯Ýr˜OÕ¤¡:è1=_ÈÈ.]ŸW¿Áø3¶Æ[®qµÚz"CEMÞ8øùn·»î¾df¡Œ_ž#‡v8ÜF¿Æfdrô`m¹pßOÔcû;ùü9ºç/o¶«Å8«¬»dý(²/ÝæÆ´æ®“·vÛü ˜QÜïÛª6u“eÙzÞ1VVÐ§IÏ²õö'«Ê#3¾ª)Kk%+)ÒÑ§Ï­Ö ó|_çÁYCÍ>´ÂÓ
]ŸV¶ˆår…1ÎÛŸmÌ¨-4YÈÂ[_µÀôf÷¿“Œ0³ùÉOÞë“$ô²þÒÓî¼ÙŽy<ZtÓö»å+®Æý¾‹Ñ²áÑaXýŠljœœ-c™¸c¦ð”?ûCó[þô/o/†kYRdõ¶ûí{vÝ[îÄm±³ÓGˆ·¼ª5}iY•ÑVN¾›-†JœOaœ¯Ò]¿ee¤w›zr,Yå:QL–™ÞFá<y…‡oä­0-²Ûñœò4Æ46×œÃ^Èf·ŽvÓ¦,{Ã9õÈÒÏZùð&ã´[¯2Ÿ¤Ö;3°vã¢·¹þë¸±"·8T¿Ð}™u+NÄ¸ánÙ½ŒÐ—wî·›åÖƒKnÇÄÕ‘…«ôÚQ³ÝŠýÏÙµÎo˜P0ðaðÜÊ†1îiºØÏTÿ†7ñðºe³•vÎƒiÅÞÑC’=˜§mä_åˆøÁÚbG¬þÂªþ²ÉÇš8óÕé¹önõâ·¿ŸøUVºŸÔfñÓ+§Ä¼Ðw
pú´£ŸDú‡ú|9¦È3I–k1²ïûì‡ÂQýã‘N	Þ:ò“ïb»êe»@g{®·èˆwFÀ­ÏÛ…Þ½g<WçCFÌê®êKºÉs2|ž9Ø¾DÇ:&D&òµIZµµvÜþ"ÏI˜ûÜË}‹«ÛµK^cý‘TÇ¿ƒ3?ý\·æ×.JzâÉ›N«è^=Ö­¿÷ëûòY%”dZ9´÷ZÄÕXet\´ÝrÕŠ–ü7¼^ÌVºýÊªÃ/½fÖ×L]õOO
˜{¢ÿöýßoß¾ýÅÎ
H      e   C   xœ+200äò÷qwtñõôãtLÉÍÌË,.)J,É/â*200‚È:‡‡øûºq:——äç¦qÅèqqq ^A˜      f      xœ3â,200â25Ð†ÊJÇèqqq v’9      d   H  xœmÉr‚@E×ð.\7Ý ƒ;QhlÑ`‰€ZÙ4‚@dA	4!•E–ïÞªsÞå™{VòÌ˜§cÇŠzq~Åú6æ­[Ir"US€÷²C3D¾#­c¬KËÈoŸZtˆ{€ÌÎEÞ18ãôÑè	nX1´.:’ÅD_WS'í±äœCênÂ 7 Ä)[{^N«Dœ/UÅ2mõâÑj<Ó¥~Ü*ÚÐŒÎ¢Œ&éËuì›‘ÚW£íw×KÑÏShÄ@íDûˆ³¹ÓÅýê†H'(T9—»lîò6N
ÿã¦¾Y¡5@þÈöaÝŒžÜ†'‚‚¡(K
ä=áWy52·ÏIn+¶vÂ€®êJ·¢É0§ííÄ¼Á‰‰2Úê	{‚i½vö[øßÂÞúX–ý¬H„m      o   ,   xœ3â442#N·ü’üxC½¬‚tNO?OGG_ÇNC®=... Á_	      @    y           0    0    ENCODING    ENCODING        SET client_encoding = 'UTF8';
                      false            z           0    0 
   STDSTRINGS 
   STDSTRINGS     (   SET standard_conforming_strings = 'on';
                      false            {           0    0 
   SEARCHPATH 
   SEARCHPATH     8   SELECT pg_catalog.set_config('search_path', '', false);
                      false            |           1262    40866    db_first_project    DATABASE     ˜   CREATE DATABASE db_first_project WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'English_Indonesia.1252' LC_CTYPE = 'English_Indonesia.1252';
     DROP DATABASE db_first_project;
                pg_write_server_files    false            Õ            1259    41217    dat_cart    TABLE     V   CREATE TABLE public.dat_cart (
    id bigint NOT NULL,
    id_user bigint NOT NULL
);
    DROP TABLE public.dat_cart;
       public         heap    postgres    false            Ô            1259    41215    dat_cart_id_seq    SEQUENCE     Ï   ALTER TABLE public.dat_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    213            Ø            1259    41387    dat_cart_produk    TABLE     ¨   CREATE TABLE public.dat_cart_produk (
    id_cart bigint NOT NULL,
    id_produk character varying(5) NOT NULL,
    jumlah_item numeric(5,0),
    id bigint NOT NULL
);
 #   DROP TABLE public.dat_cart_produk;
       public         heap    postgres    false            Ù            1259    41407    dat_cart_produk_id_seq    SEQUENCE     Ý   ALTER TABLE public.dat_cart_produk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_cart_produk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    216            Ò            1259    41124    dat_gambar_produk    TABLE     ”   CREATE TABLE public.dat_gambar_produk (
    id bigint NOT NULL,
    nama_gambar character varying(216),
    id_produk character varying NOT NULL
);
 %   DROP TABLE public.dat_gambar_produk;
       public         heap    postgres    false            Ó            1259    41127    dat_gambar_produk_id_seq    SEQUENCE     á   ALTER TABLE public.dat_gambar_produk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_gambar_produk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    210            Ñ            1259    41113    dat_kategori_produk    TABLE     w   CREATE TABLE public.dat_kategori_produk (
    id character varying(4) NOT NULL,
    kategori character varying(128)
);
 '   DROP TABLE public.dat_kategori_produk;
       public         heap    postgres    false            Ý            1259    41733    dat_notif_user    TABLE       CREATE TABLE public.dat_notif_user (
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    expired_date timestamp(0) with time zone NOT NULL,
    id_user bigint NOT NULL,
    action character varying(32) NOT NULL,
    id bigint NOT NULL
);
 "   DROP TABLE public.dat_notif_user;
       public         heap    postgres    false            Þ            1259    41745    dat_notif_user_id_seq    SEQUENCE     Û   ALTER TABLE public.dat_notif_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dat_notif_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    221            Ð            1259    41107 
   dat_produk    TABLE       CREATE TABLE public.dat_produk (
    id character varying(5) DEFAULT to_char(nextval('public.produk_seq'::regclass), '"P"fm000'::text) NOT NULL,
    kategori_produk character varying(4),
    nama_produk character varying(512),
    harga_produk numeric(15,0),
    stok_produk numeric(4,0),
    foto_produk1 character varying(512),
    foto_produk2 character varying(512),
    foto_produk3 character varying(512),
    foto_produk4 character varying(512),
    foto_produk5 character varying(512),
    deskripsi_produk character varying
);
    DROP TABLE public.dat_produk;
       public         heap    postgres    false            Ú            1259    41686    oauth_access_token    TABLE       CREATE TABLE public.oauth_access_token (
    token_id character varying(256),
    token bytea,
    authentication_id character varying(256),
    user_name character varying(256),
    client_id character varying(256),
    authentication bytea,
    refresh_token character varying(256)
);
 &   DROP TABLE public.oauth_access_token;
       public         heap    postgres    false            Î            1259    41080    oauth_client_details    TABLE     {  CREATE TABLE public.oauth_client_details (
    client_id character varying(256) NOT NULL,
    resource_ids character varying(256),
    client_secret character varying(256),
    scope character varying(256),
    authorized_grant_types character varying(256),
    web_server_redirect_uri character varying(256),
    autoapprove character varying(256),
    access_token_validity numeric(11,0) DEFAULT NULL::numeric,
    refresh_token_validity numeric(11,0) DEFAULT NULL::numeric,
    authorities character varying(256) DEFAULT NULL::character varying,
    additional_information character varying(4096) DEFAULT NULL::character varying
);
 (   DROP TABLE public.oauth_client_details;
       public         heap    postgres    false            Û            1259    41693    oauth_client_token    TABLE     Û   CREATE TABLE public.oauth_client_token (
    token_id character varying(256),
    token bytea,
    authentication_id character varying(256),
    user_name character varying(256),
    client_id character varying(256)
);
 &   DROP TABLE public.oauth_client_token;
       public         heap    postgres    false            Ü            1259    41699    oauth_refresh_token    TABLE     |   CREATE TABLE public.oauth_refresh_token (
    token_id character varying(256),
    token bytea,
    authentication bytea
);
 '   DROP TABLE public.oauth_refresh_token;
       public         heap    postgres    false            Ë            1259    41037    s_roles    TABLE     ¡   CREATE TABLE public.s_roles (
    id_role character varying(36) NOT NULL,
    name character varying(255) NOT NULL,
    label character varying(255) NOT NULL
);
    DROP TABLE public.s_roles;
       public         heap    postgres    false            Ì            1259    41047    s_user_roles    TABLE     n   CREATE TABLE public.s_user_roles (
    id_user bigint NOT NULL,
    id_role character varying(36) NOT NULL
);
     DROP TABLE public.s_user_roles;
       public         heap    postgres    false            Ê            1259    41015    s_users    TABLE     ?  CREATE TABLE public.s_users (
    id_user bigint DEFAULT nextval('public.s_users_seq'::regclass) NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fullname character varying(255) NOT NULL,
    active boolean NOT NULL
);
    DROP TABLE public.s_users;
       public         heap    postgres    false            ×            1259    41236    s_users_details    TABLE     Á   CREATE TABLE public.s_users_details (
    id bigint NOT NULL,
    no_hp character varying(13),
    foto_profil character varying(216),
    alamat character varying(2048),
    id_user bigint
);
 #   DROP TABLE public.s_users_details;
       public         heap    postgres    false            Ö            1259    41234    s_users_details_id_seq    SEQUENCE     Ý   ALTER TABLE public.s_users_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.s_users_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    215            m          0    41217    dat_cart 
   TABLE DATA           /   COPY public.dat_cart (id, id_user) FROM stdin;
    public          postgres    false    213            p          0    41387    dat_cart_produk 
   TABLE DATA           N   COPY public.dat_cart_produk (id_cart, id_produk, jumlah_item, id) FROM stdin;
    public          postgres    false    216   (        j          0    41124    dat_gambar_produk 
   TABLE DATA           G   COPY public.dat_gambar_produk (id, nama_gambar, id_produk) FROM stdin;
    public          postgres    false    210   N        i          0    41113    dat_kategori_produk 
   TABLE DATA           ;   COPY public.dat_kategori_produk (id, kategori) FROM stdin;
    public          postgres    false    209           u          0    41733    dat_notif_user 
   TABLE DATA           \   COPY public.dat_notif_user (username, email, expired_date, id_user, action, id) FROM stdin;
    public          postgres    false    221   =        h          0    41107 
   dat_produk 
   TABLE DATA           ¹   COPY public.dat_produk (id, kategori_produk, nama_produk, harga_produk, stok_produk, foto_produk1, foto_produk2, foto_produk3, foto_produk4, foto_produk5, deskripsi_produk) FROM stdin;
    public          postgres    false    208   a        r          0    41686    oauth_access_token 
   TABLE DATA           …   COPY public.oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) FROM stdin;
    public          postgres    false    218   $       g          0    41080    oauth_client_details 
   TABLE DATA           ï   COPY public.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, autoapprove, access_token_validity, refresh_token_validity, authorities, additional_information) FROM stdin;
    public          postgres    false    206   w       s          0    41693    oauth_client_token 
   TABLE DATA           f   COPY public.oauth_client_token (token_id, token, authentication_id, user_name, client_id) FROM stdin;
    public          postgres    false    219   þ        t          0    41699    oauth_refresh_token 
   TABLE DATA           N   COPY public.oauth_refresh_token (token_id, token, authentication) FROM stdin;
    public          postgres    false    220           e          0    41037    s_roles 
   TABLE DATA           7   COPY public.s_roles (id_role, name, label) FROM stdin;
    public          postgres    false    203   3       f          0    41047    s_user_roles 
   TABLE DATA           8   COPY public.s_user_roles (id_user, id_role) FROM stdin;
    public          postgres    false    204   M        d          0    41015    s_users 
   TABLE DATA           W   COPY public.s_users (id_user, username, password, email, fullname, active) FROM stdin;
    public          postgres    false    202   '        o          0    41236    s_users_details 
   TABLE DATA           R   COPY public.s_users_details (id, no_hp, foto_profil, alamat, id_user) FROM stdin;
    public          postgres    false    215   R       }           0    0    dat_cart_id_seq    SEQUENCE SET     >   SELECT pg_catalog.setval('public.dat_cart_id_seq', 63, true);
          public          postgres    false    212            ~           0    0    dat_cart_produk_id_seq    SEQUENCE SET     E   SELECT pg_catalog.setval('public.dat_cart_produk_id_seq', 26, true);
          public          postgres    false    217                       0    0    dat_gambar_produk_id_seq    SEQUENCE SET     G   SELECT pg_catalog.setval('public.dat_gambar_produk_id_seq', 37, true);
          public          postgres    false    211            €           0    0    dat_notif_user_id_seq    SEQUENCE SET     C   SELECT pg_catalog.setval('public.dat_notif_user_id_seq', 6, true);
          public          postgres    false    222                       0    0    s_users_details_id_seq    SEQUENCE SET     D   SELECT pg_catalog.setval('public.s_users_details_id_seq', 2, true);
          public          postgres    false    214            Ö
           2606    41221    dat_cart dat_cart_pk 
   CONSTRAINT     R   ALTER TABLE ONLY public.dat_cart
    ADD CONSTRAINT dat_cart_pk PRIMARY KEY (id);
 >   ALTER TABLE ONLY public.dat_cart DROP CONSTRAINT dat_cart_pk;
       public            postgres    false    213            Þ
           2606    41417 "   dat_cart_produk dat_cart_produk_pk 
   CONSTRAINT     `   ALTER TABLE ONLY public.dat_cart_produk
    ADD CONSTRAINT dat_cart_produk_pk PRIMARY KEY (id);
 L   ALTER TABLE ONLY public.dat_cart_produk DROP CONSTRAINT dat_cart_produk_pk;
       public            postgres    false    216            Ø
           2606    41591    dat_cart dat_cart_un 
   CONSTRAINT     R   ALTER TABLE ONLY public.dat_cart
    ADD CONSTRAINT dat_cart_un UNIQUE (id_user);
 >   ALTER TABLE ONLY public.dat_cart DROP CONSTRAINT dat_cart_un;
       public            postgres    false    213            Ô
           2606    41136 &   dat_gambar_produk dat_gambar_produk_pk 
   CONSTRAINT     d   ALTER TABLE ONLY public.dat_gambar_produk
    ADD CONSTRAINT dat_gambar_produk_pk PRIMARY KEY (id);
 P   ALTER TABLE ONLY public.dat_gambar_produk DROP CONSTRAINT dat_gambar_produk_pk;
       public            postgres    false    210            Ò
           2606    41117 *   dat_kategori_produk dat_kategori_produk_pk 
   CONSTRAINT     h   ALTER TABLE ONLY public.dat_kategori_produk
    ADD CONSTRAINT dat_kategori_produk_pk PRIMARY KEY (id);
 T   ALTER TABLE ONLY public.dat_kategori_produk DROP CONSTRAINT dat_kategori_produk_pk;
       public            postgres    false    209            Î
           2606    41087 .   oauth_client_details oauth_client_details_pkey 
   CONSTRAINT     s   ALTER TABLE ONLY public.oauth_client_details
    ADD CONSTRAINT oauth_client_details_pkey PRIMARY KEY (client_id);
 X   ALTER TABLE ONLY public.oauth_client_details DROP CONSTRAINT oauth_client_details_pkey;
       public            postgres    false    206            Ð
           2606    41112    dat_produk produk_pkey 
   CONSTRAINT     T   ALTER TABLE ONLY public.dat_produk
    ADD CONSTRAINT produk_pkey PRIMARY KEY (id);
 @   ALTER TABLE ONLY public.dat_produk DROP CONSTRAINT produk_pkey;
       public            postgres    false    208            È
           2606    41046    s_roles s_role_name_key 
   CONSTRAINT     R   ALTER TABLE ONLY public.s_roles
    ADD CONSTRAINT s_role_name_key UNIQUE (name);
 A   ALTER TABLE ONLY public.s_roles DROP CONSTRAINT s_role_name_key;
       public            postgres    false    203            Ê
           2606    41044    s_roles s_role_pkey 
   CONSTRAINT     V   ALTER TABLE ONLY public.s_roles
    ADD CONSTRAINT s_role_pkey PRIMARY KEY (id_role);
 =   ALTER TABLE ONLY public.s_roles DROP CONSTRAINT s_role_pkey;
       public            postgres    false    203            Â
           2606    41026    s_users s_user_email_key 
   CONSTRAINT     T   ALTER TABLE ONLY public.s_users
    ADD CONSTRAINT s_user_email_key UNIQUE (email);
 B   ALTER TABLE ONLY public.s_users DROP CONSTRAINT s_user_email_key;
       public            postgres    false    202            Ä
           2606    41022    s_users s_user_pkey 
   CONSTRAINT     V   ALTER TABLE ONLY public.s_users
    ADD CONSTRAINT s_user_pkey PRIMARY KEY (id_user);
 =   ALTER TABLE ONLY public.s_users DROP CONSTRAINT s_user_pkey;
       public            postgres    false    202            Ì
           2606    41051    s_user_roles s_user_role_pkey 
   CONSTRAINT     i   ALTER TABLE ONLY public.s_user_roles
    ADD CONSTRAINT s_user_role_pkey PRIMARY KEY (id_user, id_role);
 G   ALTER TABLE ONLY public.s_user_roles DROP CONSTRAINT s_user_role_pkey;
       public            postgres    false    204    204            Æ
           2606    41024    s_users s_user_username_key 
   CONSTRAINT     Z   ALTER TABLE ONLY public.s_users
    ADD CONSTRAINT s_user_username_key UNIQUE (username);
 E   ALTER TABLE ONLY public.s_users DROP CONSTRAINT s_user_username_key;
       public            postgres    false    202            Ú
           2606    41243 "   s_users_details s_users_details_pk 
   CONSTRAINT     `   ALTER TABLE ONLY public.s_users_details
    ADD CONSTRAINT s_users_details_pk PRIMARY KEY (id);
 L   ALTER TABLE ONLY public.s_users_details DROP CONSTRAINT s_users_details_pk;
       public            postgres    false    215            Ü
           2606    41245 "   s_users_details s_users_details_un 
   CONSTRAINT     `   ALTER TABLE ONLY public.s_users_details
    ADD CONSTRAINT s_users_details_un UNIQUE (id_user);
 L   ALTER TABLE ONLY public.s_users_details DROP CONSTRAINT s_users_details_un;
       public            postgres    false    215            â
           2606    41356    dat_cart dat_cart_fk 
   FK CONSTRAINT     z   ALTER TABLE ONLY public.dat_cart
    ADD CONSTRAINT dat_cart_fk FOREIGN KEY (id_user) REFERENCES public.s_users(id_user);
 >   ALTER TABLE ONLY public.dat_cart DROP CONSTRAINT dat_cart_fk;
       public          postgres    false    213    202    2756            ä
           2606    41390 "   dat_cart_produk dat_cart_produk_fk 
   FK CONSTRAINT     ¬   ALTER TABLE ONLY public.dat_cart_produk
    ADD CONSTRAINT dat_cart_produk_fk FOREIGN KEY (id_produk) REFERENCES public.dat_produk(id) ON UPDATE CASCADE ON DELETE CASCADE;
 L   ALTER TABLE ONLY public.dat_cart_produk DROP CONSTRAINT dat_cart_produk_fk;
       public          postgres    false    208    2768    216            å
           2606    41395 $   dat_cart_produk dat_cart_produk_fk_1 
   FK CONSTRAINT     ª   ALTER TABLE ONLY public.dat_cart_produk
    ADD CONSTRAINT dat_cart_produk_fk_1 FOREIGN KEY (id_cart) REFERENCES public.dat_cart(id) ON UPDATE CASCADE ON DELETE CASCADE;
 N   ALTER TABLE ONLY public.dat_cart_produk DROP CONSTRAINT dat_cart_produk_fk_1;
       public          postgres    false    213    2774    216            á
           2606    41382    dat_produk dat_produk_fk 
   FK CONSTRAINT     ²   ALTER TABLE ONLY public.dat_produk
    ADD CONSTRAINT dat_produk_fk FOREIGN KEY (kategori_produk) REFERENCES public.dat_kategori_produk(id) ON UPDATE CASCADE ON DELETE RESTRICT;
 B   ALTER TABLE ONLY public.dat_produk DROP CONSTRAINT dat_produk_fk;
       public          postgres    false    2770    209    208            à
           2606    41057 %   s_user_roles s_user_role_id_role_fkey 
   FK CONSTRAINT     ‹   ALTER TABLE ONLY public.s_user_roles
    ADD CONSTRAINT s_user_role_id_role_fkey FOREIGN KEY (id_role) REFERENCES public.s_roles(id_role);
 O   ALTER TABLE ONLY public.s_user_roles DROP CONSTRAINT s_user_role_id_role_fkey;
       public          postgres    false    204    2762    203            ß
           2606    41052 %   s_user_roles s_user_role_id_user_fkey 
   FK CONSTRAINT     ‹   ALTER TABLE ONLY public.s_user_roles
    ADD CONSTRAINT s_user_role_id_user_fkey FOREIGN KEY (id_user) REFERENCES public.s_users(id_user);
 O   ALTER TABLE ONLY public.s_user_roles DROP CONSTRAINT s_user_role_id_user_fkey;
       public          postgres    false    2756    202    204            ã
           2606    41251 "   s_users_details s_users_details_fk 
   FK CONSTRAINT     ¬   ALTER TABLE ONLY public.s_users_details
    ADD CONSTRAINT s_users_details_fk FOREIGN KEY (id_user) REFERENCES public.s_users(id_user) ON UPDATE CASCADE ON DELETE CASCADE;
 L   ALTER TABLE ONLY public.s_users_details DROP CONSTRAINT s_users_details_fk;
       public          postgres    false    215    2756    202           