FROM node:15.11-alpine as builder

WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run ng build --prod --aot --output-hashing=all

# Stage 2 - Deploy with NGNIX
FROM nginx:1.19.7-alpine

COPY --from=builder /usr/src/app/dist/client-app /var/www
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]